# Generated by Django 2.1 on 2018-08-17 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
